<h1>NUMPY</h1>

In [2]:
import numpy as np
import sys

<h1>The Basics</h1>

In [14]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
a.ndim

1

In [12]:
# Get Shape
b.shape

(2, 3)

In [15]:
# Get Type
a.dtype

dtype('int16')

In [16]:
# Get Size
a.itemsize

2

In [17]:
# Get total size
a.size
a.nbytes

3

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r, c]
a[1,5]
a[1, -2]

13

In [21]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# [start_index:ending_index:setp_size]
a[0,1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5] = 20
print(a)



[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [27]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specific element
b[:,1:,]

array([[[3, 4]],

       [[7, 8]]])

In [32]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


<h1>Initialising Different Types of Arrays</h1>

In [35]:
# All 0s matrix
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [36]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [37]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [38]:
# Any other number (full_like)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [40]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.16816752, 0.78314958],
       [0.42955642, 0.83273462],
       [0.77211672, 0.61314396],
       [0.15798942, 0.92305062]])

In [42]:
np.random.random_sample(a.shape)

array([[0.77115767, 0.87312276, 0.97902329, 0.17808195, 0.1360622 ,
        0.8074453 , 0.63119565],
       [0.79074197, 0.19857573, 0.24992921, 0.86240951, 0.91699753,
        0.3163584 , 0.3035942 ]])

In [43]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[5, 4, 3],
       [2, 3, 4],
       [1, 2, 0]])

In [44]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


<h1>Practice</h1>

In [70]:
c = np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
c[1,1:4] = [0,0,0]
c[2,1:4] = [0,9,0]
c[3,1:4] = [0,0,0]
print(c)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:-1,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
# Copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


<h1>Mathematics</h1>

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
b = np.array([1,0,1,0])

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.sin(a)

# Take the cos
np.cos(a)

In [76]:
# Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [77]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c.np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

<h1>Statistics</h1>

In [78]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.min(stats)

1

In [80]:
np.max(stats, axis=1)

array([3, 6])

In [81]:
np.sum(stats,axis=1)

array([ 6, 15])

<h1>Reorganizing Arrays</h1>

In [82]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [84]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

<h1>Miscellaneous</h1>

## Load Data from File

In [91]:
filedata = np.genfromtxt('C:\\Users\\GRIZELLE\\GitHub Projects\\100-Days-Of-Coding-ML\\Day 23\\data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

## Boolean Masking and Avanced Indexing

In [93]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [92]:
# You can index index with a list in numpy 
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])